//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerProyectoMVC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_FinalEntities : DbContext
    {
        public Proyecto_FinalEntities()
            : base("name=Proyecto_FinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Plan_Service> Plan_Service { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<TasaID> TasaIDs { get; set; }
        public virtual DbSet<Table> Tables { get; set; }

        public System.Data.Entity.DbSet<MiPrimerProyectoMVC.Controllers.RNC12> RNC12 { get; set; }
    }
}
