//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerProyectoMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Service
    {
        public int Plan_Service1 { get; set; }
        public int PlanID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Service Service { get; set; }
    }
}
