//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerProyectoMVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionID { get; set; }
        public int PlanID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public bool IsExpired { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
