//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimerProyectoMVC.Model
{
    using global::Model;
    using Helper;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Usuario
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public int Rol_id { get; set; }
    
        public virtual Rol Rol { get; set; }


        public ResponseModel Autenticarse()
        {
            var rm = new ResponseModel();

            try
            {
                using (var ctx = new BaseDeDatosEntities())
                {
                    var usuario = ctx.Usuarios.Where(x => x.Correo == this.Correo && x.Password == this.Password).SingleOrDefault();
                    if (usuario != null)
                    {
                        SessionHelper.AddUserToSession(usuario.id.ToString());
                        rm.SetResponse(true);
                    }
                    else
                    {
                        rm.SetResponse(false, "Acceso denegado al sistema");
                    }
                }
            }
            catch (Exception e)
            {
                throw;
            }
            return rm;
        }

        public Usuario Obtener(int id)
        {
            var usuario = new Usuario();

            try
            {
                using (var ctx = new BaseDeDatosEntities())
                {
                    ctx.Configuration.LazyLoadingEnabled = false;

                    usuario = ctx.Usuarios.Include("Rol")
                                         .Include("Rol.Permiso")
                                         .Where(x => x.id == id).SingleOrDefault();
                }
            }
            catch (Exception e)
            {
                throw;
            }

            return usuario;
        }
    }
}
